package mil.nga.country_name.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-22T19:00:19.131Z
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "mil:nga:country_name:v2", name = "CountryName")
@XmlSeeAlso({us.gov.ic.ism.v2.ObjectFactory.class, mil.nga.security.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CountryName {

    @WebMethod
    @WebResult(name = "GetCountryNamesResponse", targetNamespace = "mil:nga:country_name:v2", partName = "result")
    public GetCountryNamesResponse getCountryNames(
        @WebParam(partName = "parameters", name = "GetCountryNames", targetNamespace = "mil:nga:country_name:v2")
        GetCountryNames parameters
    );

    @WebMethod
    @WebResult(name = "GetParameterInfoResponse", targetNamespace = "mil:nga:country_name:v2", partName = "result")
    public GetParameterInfoResponse getParameterInfo(
        @WebParam(partName = "parameters", name = "GetParameterInfo", targetNamespace = "mil:nga:country_name:v2")
        GetParameterInfo parameters
    );
}
